#!/usr/bin/env sh

createdb commitz-dev
export DATABASE_URL=postgres://localhost/commitz-dev
sequel -m migrations postgres://localhost/commitz-dev
cat <<END >.env
DATABASE_URL='postgres://localhost/commitz-dev'
GITHUB_OAUTH_TOKEN='<YOUR OAUTH TOKEN HERE>'
GITHUB_ORG='heroku'
BACKFILL_SINCE='2011-01-01 00:00:00 UTC'
END
